Block Dense QR
rioyokotalab/Hatrix pull request #2
Opened 2021-04-23 05:25 UTC by wawando

- Added LAPACK subroutines: "dtrmm" aka `triangular_matmul`, "geqrt" aka `householder_qr_compact_wy`, and "dlarfb" aka `apply_block_reflector` along with the unit-tests
- Added `2x2_BlockDense_QR` example

2021-04-24 01:48 UTC, derpda requested changes
Good stuff! 
Aside from the comments I already added to the code, here's a few suggestions:
 - The unit test really isn't a unit test - it's an example of the code (like `construct_BLR_matrix`)
   You could make it an example executable that just does some checking on its calculations.
 - We should have separate unit tests for larfb, geqrt. 
   That way we can know if one of them breaks
 - I added convenience methods for matrix initialization.
   Its probably best to use randomized input (and add special things like large diagonals).

2021-04-24 01:48 UTC, derpda commented on src/functions/lapack.cpp
> +void larfb(const Matrix& V, const Matrix& T, Matrix& C, bool trans) {
Same as with dgeqrt, assertions would be good here!

2021-04-24 01:48 UTC, derpda commented on src/functions/lapack.cpp
> +void geqrt(Matrix& A, Matrix& T) {
Some assertions on sizes might be good! 
That way people can know what the function expects by looking at the code.
We don't have those consistently in the code yet, but really should since they don't affect performance and help with debugging.

2021-04-24 01:48 UTC, derpda commented on include/Hatrix/functions/lapack.h
> +void geqrt(Matrix& A, Matrix& T);
Maybe we can figure out better names here!
I looked it up on the Netlib documentation, but don't fully understand what the difference between the methods are.
 - dgeqr
 - dgeqr2
 - dgeqr2p
 - dgeqrf
 - dgeqrfp
 - dgeqrt
 - dgeqrt2
 - dgeqrt3

I don't think we need all of them, but if we can give these functions better names (they may be long, that's ok!), then we'll have more readable code I think!

2021-04-24 01:48 UTC, derpda commented on include/Hatrix/functions/lapack.h
> +void larfb(const Matrix& V, const Matrix& T, Matrix& C, bool trans);
apply_block_reflector?
Not sure if that's an accurate name, but tells me more than `larfb` =D

2021-04-24 01:48 UTC, derpda commented on test/block_dense_qr.cpp
> +  int block_size = 4;
Lets use `int64_t` here! 
I know I made that change only very recently, but we should probably be consistent =)

2021-04-24 01:49 UTC, derpda commented
Also thanks for making this a proper PR! 
I should do that as well with my changes from now on...

2021-04-27 04:01 UTC, wawando commented on include/Hatrix/functions/lapack.h
> +void geqrt(Matrix& A, Matrix& T);
Good idea. The geqrt actually does a householder (full) QR factorization and store Q using compact WY representation. How about `householder_qr_with_compact_wy` sound?

2021-04-27 04:01 UTC, wawando commented on include/Hatrix/functions/lapack.h
> +void larfb(const Matrix& V, const Matrix& T, Matrix& C, bool trans);
Yes I think `apply_block_reflector` is a perfect name for it! :D

2021-04-27 04:39 UTC, derpda commented on include/Hatrix/functions/lapack.h
> +void geqrt(Matrix& A, Matrix& T);
`householder_qr_compact_wy` is enough I think! =D

2021-04-27 05:33 UTC, wawando commented
Thanks for the feedbacks! requested changes in the comments are done. But let me move the block dense qr to example, and  also make unit test for geqrt and larfb

2021-04-27 06:19 UTC, derpda approved these changes

2021-04-27 08:35 UTC, derpda approved these changes

2021-05-01 15:52 UTC, wawando commented
@v0dro unit tests are done, please merge to `dev` if everything works

2021-05-07 06:10 UTC, derpda requested changes
Really nice, just some simplification needed using the operators.
Also some formatting - but we should have a tool for that.

2021-05-07 06:59 UTC, wawando commented
@derpda simplification done! For the indentation, I'm not sure why but it looks good on my emacs, but somehow it looks weird on Github.

2021-05-07 07:33 UTC, rioyokota approved these changes
LGTM

2021-05-07 07:33 UTC, merged