Hss 2 level construction
rioyokotalab/Hatrix pull request #29
Opened 2021-09-03 08:19 UTC by v0dro

2021-09-03 08:39 UTC, derpda commented on run.sh
> +#!/bin/bash
Should this be committed to the repo?

2021-09-03 12:16 UTC, derpda requested changes
I think you introduced errors in the CMake code that will cause problems on Fugaku, although I haven't tested this. Either way, this PR probably shouldn't touch that part of the code.

The other comments I made are more cosmetic, but if we fix the copy assignment operator on Matrix then the code would be shorted and nicer!

2021-09-03 12:16 UTC, derpda commented on CMakeLists.txt
> +include(host_specific_settings)
I think these lines need to be before the call to `project` since the CXX compiler is possibly changed.

2021-09-03 12:16 UTC, derpda commented on examples/HSS_2level_construct.cpp
> +      for (int i = 0; i < leaf_size; ++i) {
Can be done easier by using split on to split `row_slice` into appropriate parts and just assigning `left_slice` and `right_slice` to it.
For that we'd have to change the `Matrix::operator=(const Matrix&)` operator to not create a new DataHandler, but instead properly assign. I think that would be better anyway.
Also I think some cleanup could be nice here, like using `ncols_left_slice` as the loop maximum for the first `j` loop.

2021-09-03 12:16 UTC, derpda commented on examples/HSS_2level_construct.cpp
> +      for (int j = 0; j < col_slice.cols; ++j) {
Same here as for the col slices

2021-09-03 12:16 UTC, derpda commented on examples/HSS_2level_construct.cpp
> +        for (int i = 0; i < Ugen_upper.rows; ++i) {
Same here, we should really fix the copy assignment operator so that this code can be shorter!

2021-09-03 12:16 UTC, derpda commented on examples/HSS_2level_construct.cpp
> +        for (int i = 0; i < Vgen_upper.rows; ++i) {
Same as other comments about assignment

2021-09-04 00:08 UTC, v0dro commented
Thanks for your review. I'll fix it and push my changes soon.

2021-09-04 05:13 UTC, v0dro commented on examples/HSS_2level_construct.cpp
> +      for (int i = 0; i < leaf_size; ++i) {
The splitting code is still quite unstable to handle all cases of split sizes. One of the issues is https://github.com/rioyokotalab/Hatrix/issues/30.

2021-09-04 05:14 UTC, v0dro commented on examples/HSS_2level_construct.cpp
> +      for (int i = 0; i < leaf_size; ++i) {
I've made some changes to the assignment operator but the #split() method will still need some work.

2021-09-04 05:14 UTC, v0dro commented on examples/HSS_2level_construct.cpp
> +      for (int j = 0; j < col_slice.cols; ++j) {
Commented above.

2021-09-04 05:18 UTC, v0dro commented on examples/HSS_2level_construct.cpp
> +        for (int i = 0; i < Ugen_upper.rows; ++i) {
Done.

2021-09-04 05:18 UTC, v0dro commented on examples/HSS_2level_construct.cpp
> +        for (int i = 0; i < Vgen_upper.rows; ++i) {
Done.

2021-09-04 05:20 UTC, v0dro commented
Compression results:
```
N=100 rank=5 construction error : 0.00309407
N=100 rank=10 construction error : 1.84287e-06
N=100 rank=20 construction error : 9.88587e-15
N=100 rank=25 construction error : 1.83655e-15
N=1000 rank=5 construction error : 0.0240868
N=1000 rank=10 construction error : 0.000234469
N=1000 rank=20 construction error : 1.90813e-09
N=1000 rank=25 construction error : 2.60023e-11
N=1000 rank=40 construction error : 5.34845e-15
N=1000 rank=100 construction error : 3.95292e-15
```

2021-09-04 07:30 UTC, merged